services:
  - type: web
    name: snippet-app
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
